### ISSUE TITLE
[dglo on 2011-08-26 20:42:27] : pDAQ: dash - DAQLaunch prints a confusing message if ~pdaq/config/.config file is empty

### ISSUE THREAD

**Issue by arcor** [WIPACrepo/dash#551]
Ben Riedel managed to fill the disk on expcont, and then it seems like when he deployed from access, it wrote an empty file to pDAQ_current/config/.config.  When he tried to launch, he got:

Traceback (most recent call last):
  File "/usr/local/pdaq/pDAQ_current/dash/DAQLaunch.py", line 495, in <module>
    configDir=configDir)
  File "/usr/local/pdaq/pDAQ_current/dash/DAQConfig.py", line 1423, in getClusterConfiguration
    raise xfnf
XMLFileCache.XMLFileNotFound:  in directory /usr/local/pdaq/pDAQ_current/cluster-config/src/main/xml

Steps to Reproduce: b"''"

Additional Information: b"''"

**Comment by arcor** [comment]
[dglo on 2011-08-29 17:12:35]
svn commit -m"Issue 5135: Handle empty \$PDAQ_HOME/.config files" CachedConfigName.py
Sending        CachedConfigName.py
Transmitting file data .
[commit 1d12bb5c97e870330bd802953346c933a0a353d5] Committed revision 13299.

**Comment by arcor** [comment]
[dglo on 2012-05-10 15:05:18]
These issues are all in releases
